#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged --verbose

#echo "🔍 Running Forge coverage..."
#forge coverage --report lcov > coverage.lcov
#
#echo "🔄 Converting coverage to Cobertura format..."
#yarn add -D lcov-cobertura
#lcov-cobertura -i coverage.lcov -o coverage.xml
#
#COVERAGE=$(forge coverage --report lcov | grep -oP 'Lines\s+:\s+\K\d+')
#THRESHOLD=100
#
#if [ "$COVERAGE" -lt "$THRESHOLD" ]; then
#  echo "❌ Coverage is below $THRESHOLD%. Commit rejected!"
#  exit 1
#fi

echo "✅ Code coverage check passed!"