name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Cache clean
        run: yarn cache clean

      - name: Delete node_modules
        run: rm -rf node_modules yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Copy .env files
        run: |
          echo "PINATA_API_KEY=${{ secrets.PINATA_API_KEY }}" >> .env
          echo "PINATA_SECRET_API_KEY=${{ secrets.PINATA_SECRET_API_KEY }}" >> .env
          echo "PINATA_DOMAIN=${{ secrets.PINATA_DOMAIN }}" >> .env
          cd packages/nextjs
          echo "PINATA_API_KEY=${{ secrets.PINATA_API_KEY }}" >> .env
          echo "PINATA_SECRET_API_KEY=${{ secrets.PINATA_SECRET_API_KEY }}" >> .env
          echo "PINATA_DOMAIN=${{ secrets.PINATA_DOMAIN }}" >> .env

      - name: Copy next.env files
        run: |
          echo "PINATA_DOMAIN=${{ secrets.PINATA_DOMAIN }}" >> ./packages/nextjs/.env

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run nextjs lint
        run: yarn next:lint --max-warnings=0

  type-check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check typings on nextjs
        run: yarn next:check-types

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: yarn test

  foundry:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run foundry tests with coverage
        run: forge coverage --report lcov

      - name: Check coverage
        run: |
          COVERAGE=$(forge coverage --report lcov | grep -oP 'Lines\s+:\s+\K\d+')
          if [ "$COVERAGE" -ne 100 ]; then
            echo "Coverage is not 100%. Deployment failed."
            exit 1
          fi